# Generated by Django 3.2.19 on 2023-05-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('A', 'Choice A'), ('B', 'Choice B')], default='Choice A', max_length=50),
        ),
    ]
